import os

PRODUCTION = os.getenv('PRODUCTION', False)

API_BASE_URL = "http://localhost:8080/api"
TELEGRAM_BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
ADMINS_CHAT_IDS = os.getenv('ADMINS_CHAT_IDS').split(',')

DATABASE_HOST = os.getenv('DATABASE_HOST')
DATABASE_NAME = os.getenv('DATABASE_NAME')
DATABASE_USER = os.getenv('DATABASE_USER')
DATABASE_PASSWORD = os.getenv('DATABASE_PASSWORD')
DATABASE_PORT = os.getenv('DATABASE_PORT')

ADD_TELEGRAM_REGEXP = r'[A-Za-z]{5}[0-9]{5}'